pool:
  name: Default
steps:
- task: Docker@0
  displayName: build
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: mydocker
    dockerFile: Dockerfile

- task: Docker@0
  displayName: push
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: mydocker
    action: 'Push an image'
